name: build

on:
  push:
    branches:
      - main
jobs:
  makedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step1 - Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Step2 - Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Sphinx build
        run: |
          sphinx-build source _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true

